Revert "Merge branch 'trunk' into doomsday"
This reverts commit 157e07756a90dfefda7fbd9ad615fd2109c0202d, reversing
changes made to cdcaf0482f01198fbca868b36a903ec46d16cf2c.

diff --git a/.github/workflows/build-cross.yml b/.github/workflows/build-cross.yml
--- a/.github/workflows/build-cross.yml
+++ b/.github/workflows/build-cross.yml
@@ -14,7 +14,7 @@ concurrency:
   cancel-in-progress: true
 
 env:
-  failed: 0
+  res: 0
   TESTDIR: >-
     C:\Бактріан🐫
   STR_UTF8: >-
@@ -40,7 +40,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout OCaml
-        uses: actions/checkout@v5
+        uses: actions/checkout@v4
         with:
           persist-credentials: false
       - name: Configure, build and install OCaml
@@ -50,11 +50,8 @@ jobs:
           set -x
           ./configure --disable-warn-error --disable-ocamldoc \
               --disable-ocamltest --disable-stdlib-manpages \
-              --prefix="$PREFIX" || failed=$?
-          if ((failed)) ; then set +x
-            echo ; echo "::group::config.log content ($(wc -l config.log) lines)"
-            cat config.log ; echo '::endgroup::' ; exit $failed
-          fi
+              --disable-dependency-generation --prefix="$PREFIX" || res=$?
+          if ! [ "$res" = 0 ]; then cat config.log; exit "$res"; fi
           make -j
           make install
           cd "$HOME"
@@ -83,7 +80,7 @@ jobs:
           sudo apt-get update -y
           sudo apt-get install -y gcc-mingw-w64-x86-64
       - name: Checkout OCaml
-        uses: actions/checkout@v5
+        uses: actions/checkout@v4
         with:
           submodules: true
           persist-credentials: false
@@ -91,11 +88,8 @@ jobs:
         run: |
           set -x
           ./configure --prefix="$HOME/cross" --target=x86_64-w64-mingw32 \
-              TARGET_LIBDIR="$TESTDIR" || failed=$?
-          if ((failed)) ; then set +x
-            echo ; echo "::group::config.log content ($(wc -l config.log) lines)"
-            cat config.log ; echo '::endgroup::' ; exit $failed
-          fi
+              TARGET_LIBDIR="$TESTDIR" || res=$?
+          if ! [ "$res" = 0 ]; then cat config.log; exit "$res"; fi
           # The OOM-killer may be triggered if the number of parallel
           # jobs isn't limited.
           make crossopt -j$(nproc)
@@ -157,7 +151,7 @@ jobs:
           sudo apt-get update -y
           sudo apt-get install -y gcc-aarch64-linux-gnu qemu-user
       - name: Checkout OCaml
-        uses: actions/checkout@v5
+        uses: actions/checkout@v4
         with:
           submodules: true
           persist-credentials: false
@@ -165,11 +159,8 @@ jobs:
         run: |
           set -x
           ./configure --prefix="$HOME/cross" --target=aarch64-linux-gnu \
-              || failed=$?
-          if ((failed)) ; then set +x
-            echo ; echo "::group::config.log content ($(wc -l config.log) lines)"
-            cat config.log ; echo '::endgroup::' ; exit $failed
-          fi
+              || res=$?
+          if ! [ "$res" = 0 ]; then cat config.log; exit "$res"; fi
           make crossopt -j
           make installcross
       - name: Show opt.opt configuration
@@ -200,10 +191,6 @@ jobs:
   cross-android:
     runs-on: ubuntu-latest
     needs: non-cross
-    env:
-      # https://developer.android.com/ndk/downloads#lts-downloads
-      NDK: r27d # Latest LTS Version
-      API_LEVEL: 21
     steps:
       - name: Download Artifact
         uses: actions/download-artifact@v4
@@ -221,48 +208,46 @@ jobs:
         with:
           path: |
             /home/runner/android
-          key: android-ndk-${{ env.NDK }}
+          key: android-ndk
       - name: Download the Android NDK
         run: |
           set -x
           mkdir -p "$HOME/android"
           cd "$HOME/android"
-          wget --no-verbose "https://dl.google.com/android/repository/android-ndk-$NDK-linux.zip"
-          unzip android-ndk-$NDK-linux.zip
-          rm android-ndk-$NDK-linux.zip
+          wget --no-verbose https://dl.google.com/android/repository/android-ndk-r27b-linux.zip
+          unzip android-ndk-r27b-linux.zip
+          rm android-ndk-r27b-linux.zip
         if: steps.cache.outputs.cache-hit != 'true'
       - name: Save the Android NDK to cache
         uses: actions/cache/save@v4
         with:
           path: |
             /home/runner/android
-          key: android-ndk-${{ env.NDK }}
+          key: android-ndk
         if: steps.cache.outputs.cache-hit != 'true'
       - name: Checkout OCaml
-        uses: actions/checkout@v5
+        uses: actions/checkout@v4
         with:
           persist-credentials: false
       - name: Configure, build and install Linux-to-Android OCaml
         env:
-          TARGET: x86_64-linux-android${{ env.API_LEVEL }}
-          TOOLDIR: android-ndk-${{ env.NDK }}/toolchains/llvm/prebuilt/linux-x86_64/bin
+          TARGET: x86_64-linux-android21
+          TOOLDIR: android-ndk-r27b/toolchains/llvm/prebuilt/linux-x86_64/bin
         run: |
           DIR="$HOME/android/$TOOLDIR"
           set -x
-          # `pthread_cancel` isn't available on Android, so the result
-          # program should _not_ be run with cleanup on exit (so no
-          # `c=1` in `OCAMLRUNPARAM`)
+          # Hack around the fact that pthread_cancel isn't available on Android
+          # So the result program should _not_ be run with cleanup on exit
+          # (so no `c=1` in `OCAMLRUNPARAM`)
           ./configure --prefix="$HOME/cross" --target=$TARGET \
               TARGET_LIBDIR="/dummy/directory" \
               CC="$DIR/clang --target=$TARGET" \
+              CPPFLAGS='-Dpthread_cancel=assert' \
               AR="$DIR/llvm-ar" \
               PARTIALLD="$DIR/ld -r" \
               RANLIB="$DIR/llvm-ranlib" \
-              STRIP="$DIR/llvm-strip" || failed=$?
-          if ((failed)) ; then set +x
-            echo ; echo "::group::config.log content ($(wc -l config.log) lines)"
-            cat config.log ; echo '::endgroup::' ; exit $failed
-          fi
+              STRIP="$DIR/llvm-strip" || res=$?
+          if ! [ "$res" = 0 ]; then cat config.log; exit "$res"; fi
           make crossopt -j
           make installcross
       - name: Show opt.opt configuration
@@ -280,7 +265,7 @@ jobs:
       - name: Run example
         uses: reactivecircus/android-emulator-runner@v2
         with:
-          api-level: ${{ env.API_LEVEL }}
+          api-level: 21
           arch: x86_64
           disable-animations: true
           script: |
